import Head from 'next/head';
import { useState } from 'react';
import { BsFillMoonStarsFill } from 'react-icons/bs'
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode? "dark" : ""}>
      <Head>
        <title> Ryan Salvato Portfolio</title>
        <meta name="description" content='Generated by create next app' />
        <link rel='icon' href='/favicon.icon'/>
      </Head>

      <main>
        <section className='bg-blue-700 min-h-screen'>
          <h1>hi</h1>
          <ul>
            <li></li>
            <li a href='#'>Resume</li>
          </ul>
        </section>
      </main>
    </div>
  )
}